
default: &default
  adapter: postgresql
  encoding: unicode
  database: blog_project
  pool: 5
  username: harshisgood
  password: good
  host: localhost
  port: 5432 

development:
  <<: *default
  database: blog_project
  pool: 5
  username: harshisgood
  password: good
  host: localhost
  port: 5432

test:
  <<: *default
  database: blog_test

production:
  adapter: postgresql
  encoding: unicode
  database: blog_project
  pool: 5
  username: harshisgood
  password: good
  host: localhost
  port: 5432 